visio_general:
    path:     /
    defaults: { _controller: AppBundle:General:index }


admin_tests:
    path: /tests
    defaults: { _controller: AppBundle:Test:index }


nova_linia:
    path: /nova_linia
    defaults: { _controller: AppBundle:General:newLinia }


nova_sublinia:
    path: /nova_sublinia/{id}
    defaults: { _controller: AppBundle:General:newSublinia, id : false }


editar_sublinia:
    path: /editar_sublinia/{Sublinia}
    defaults: { _controller: AppBundle:General:editSublinia }


nova_familia:
    path: /nova_familia
    defaults: { _controller: AppBundle:General:newFamilia }


nova_maquina:
    path: /nova_maquina/{maquina_id}
    defaults: { _controller: AppBundle:General:newMaquina , maquina_id : false}


afegir_maquina:
    path: /afegir_maquina/{id}
    defaults: { _controller: AppBundle:General:addMaquina }


nova_OF:
    path: /tests/nova_OF
    defaults: { _controller: AppBundle:Test:newOf }


finalitzar_OF:
    path: /tests/finalize_OF/{OF}
    defaults: { _controller : AppBundle:Test:finalizeOf}


OF_view:
    path: /tests/OF_overview/{OF_id}
    defaults: { _controller : AppBundle:Test:viewOf }


iniciar_test:
    path: /tests/test_inici/{OF}
    defaults: { _controller: AppBundle:Test:iniTest }


delete_test:
    path: /tests/borrar/{OF}
    defaults: { _controller: AppBundle:Test:deleteOF }


resultats_list_ajax:
    path: /tests/resultatsListAjax/
    defaults: { _controller: AppBundle:Test:listResultats }



reopen_result:
    path: /tests/reopen/{resultat}
    defaults: { _controller: AppBundle:Test:reopenResult , resultat_id : false}


render_result:
    path: /tests/test/{resultat_id}
    defaults: { _controller: AppBundle:Test:test , resultat_id : false}


render_result_ajax:
    path: /tests/renderResult
    defaults: { _controller: AppBundle:Test:testAjax}
    requirements:
        _method:  POST


nova_mesura_ajax:
    path: /tests/novaMesura
    defaults: { _controller: AppBundle:Test:novaMesura}



finalitzar_resultat:
    path: /tests/finalitzar_resultat
    defaults: { _controller: AppBundle:Test:endResultat}
    requirements:
        _method:  POST


delete_result:
    path: /tests/result/delete
    defaults: { _controller: AppBundle:Test:deleteResult }


delete_mesura:
    path: /tests/mesura/delete
    defaults: { _controller: AppBundle:Test:deleteMesura }


nou_resultat:
    path: /tests/new
    defaults: { _controller: AppBundle:Test:newTest }
    requirements:
        _method:  POST

tests_historial:
    path: /tests/historial
    defaults: { _controller: AppBundle:Test:showHistorial }


llegir_mesura:
    path: /llegir
    defaults: { _controller: AppBundle:Test:llegirMesura }
   

maquina_report:
    path: /tests/report/maquina/{OF}/{maquina}
    defaults: { _controller: AppBundle:Test:maquinaReport }