<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PesRepository extends EntityRepository
{
}
