<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TimeORepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeORepository extends EntityRepository
{
}
